import type { Metadata } from "next";
import { Roboto_Condensed as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "../styles/globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Game Cards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased py-6 md:py-8 lg:py-10",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
